### ISSUE TITLE
The "Baby-version" Interface of Collocation and KWIC 

### ISSUE THREAD

**Issue by gelan890926** [writecrow/corpus_backend#1]
Hi Mark and Bradley, 
I'm posting this issue to share a simplified version of a corpus interface I wrote for a PHP class a year ago. This interface covers two functions: (1) KWIC (keyword in context) (2) Collocation. 

The second function covers some calculations that might be useful for our Crow prototype interface: 
- MI score: a score to quantify the closeness/similarity among multiple words. 
- T score: a standard score to test the significance in the difference between/among frequencies. 

The Codes are here:
# The interface file (frontend)
- http://web.ics.purdue.edu/~lan12/f27.html
- http://web.ics.purdue.edu/~lan12/f27.txt

# The calculation file (backend): 
- http://web.ics.purdue.edu/~lan12/f27_1.php
- http://web.ics.purdue.edu/~lan12/f27_1.txt

# See more information for the two scores:
- https://en.wikipedia.org/wiki/Mutual_information
- https://en.wikipedia.org/wiki/Standard_score

Please let me know if the PHP codes/part of the codes can be integrated into this folder.

**Comment by markfullmer** [comment]
Hi @gelan890926, nice work! Since you're linking to the files as hosted on web.ics.purdue.edu, we won't be able to see the contents of the PHP code just yet. 

Typically, on Github, people follow a 1 project : 1 repository structure, so I think your 'baby corpus interface' would best be put in its own Github repository, rather than within the `corpus_backend`, repository. You could either add this in your personal account, or we could create a new repository in the writecrow organization. @cbdilger , do you have any thoughts on which location would be more appropriate for this?

**Comment by cbdilger** [comment]
I'd love to see this as a new Writecrow repo! Then I can easily test it and make sure I actually learned this GitHub stuff.

**Comment by markfullmer** [comment]
Okay! I'll create a new repository, then @gelan890926 can do the work of writing the initial code to the repository, and @cbdilger and I and anyone else can review from there.

Given the functionality, I'd propose a Github repository name of "Corpus Collocation & Keyword Finder," with the machine name `writecrow/collocation_keyword_finder`. We'd then use Github labels to indicate that this is written in PHP. Let me know what y'all think.

@gelan890926 , once I've created it, you'll also want to add a LICENSE file and README.md to the repository.

**Comment by gelan890926** [comment]
Thanks, Bradley and Mark. Once thing to confirm: for LICENSE and README, I can just simply copy/paste them from other Github repository, and then put it in the new repository, right?

**Comment by markfullmer** [comment]
The LICENSE should be a straightforward copy-paste, yes. The README.md should follow the same format of, say, https://github.com/writecrow/lorem_gutenberg/blob/master/README.md or https://github.com/writecrow/tag_converter/blob/master/README.md , but should be tailored to describe your specific application.

The repository is created: https://github.com/writecrow/collocation_keyword_finder  -- have at adding the initial files, and we'll get to reviewing them!
